#!/bin/bash
echo "redsPUSH DB user create"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE} DEFAULT CHARACTER SET UTF8"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE USER IF NOT EXISTS ${MYSQL_USER}@'%'  IDENTIFIED BY '${MYSQL_PASSWORD}'"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@'%' IDENTIFIED BY '${MYSQL_PASSWORD}' WITH GRANT OPTION"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}' WITH GRANT OPTION"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "GRANT USAGE ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@'%'"

#echo "redsPUSH DB all schema import"
#mysql -u root -p$MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/dbs.import
