-- --------------------------------------------------------
-- 호스트:                          eberry.co.kr
-- 서버 버전:                        10.3.11-MariaDB - MariaDB Server
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 프로시저 REDSPUSH.GET_BOARD_LIST 구조 내보내기
DELIMITER //
CREATE DEFINER=`redspush`@`%` PROCEDURE `GET_BOARD_LIST`(
	IN `P_PROC_ID` VARCHAR(30)     ,
	IN `P_BRD_CD` VARCHAR(5)   ,
	IN `P_START_NO` INT				     ,
	IN `P_PAGE_NO` INT				     ,
	IN `P_TYPE` CHAR(1)     ,
	IN `P_KEYWORD` VARCHAR(50)     ,
	OUT `P_BOARD_CNT` INT             ,
	OUT `P_RESULT_ID` INT             ,
	OUT `P_MESSAGE` TINYTEXT
 


)
BEGIN

    DECLARE SQLSTRING   TEXT;
    DECLARE CNTSTRING   TEXT;
    DECLARE O_COUNT      INT;
        
    SET SQLSTRING = "";  
    SET CNTSTRING = "";
    SET O_COUNT = 0;
    
    SET P_RESULT_ID= 0;
    SET P_MESSAGE= "정상적으로 처리되었습니다.";

    IF  P_PROC_ID = 'GET_BOARD_LIST' THEN       

        SET @EXEC_BOARD_SEQ_NO = P_BRD_CD;
        SET @EXEC_ST = P_START_NO;
        SET @EXEC_CNT = P_PAGE_NO;            
        SET @ROWNUM = P_START_NO;
        
        SET CNTSTRING = CONCAT(CNTSTRING, "SELECT  COUNT(A.CNTS_SEQ_NO) \n");	    
        SET CNTSTRING = CONCAT(CNTSTRING, "  INTO    @P_CNT \n");	    
        SET CNTSTRING = CONCAT(CNTSTRING, "  FROM BD_BOARD A \n");	    
        SET CNTSTRING = CONCAT(CNTSTRING, "WHERE A.BRD_CD = ? \n");	
		      
    	  IF P_TYPE = '1' THEN
            SET @EXEC_KEYWORD  = P_KEYWORD;
            SET CNTSTRING = CONCAT(CNTSTRING, "AND    A.CNTS_SUBJ LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
        ELSEIF P_TYPE = '2' THEN
            SET @EXEC_KEYWORD  = P_KEYWORD;
            SET CNTSTRING = CONCAT(CNTSTRING, "AND    A.CNTS_MSG LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
        ELSEIF P_TYPE = '3' THEN
            SET @EXEC_KEYWORD  = P_KEYWORD;
            SET CNTSTRING = CONCAT(CNTSTRING, "AND    (A.CNTS_SUBJ LIKE CONCAT('%', @EXEC_KEYWORD , '%') OR A.CNTS_MSG LIKE CONCAT('%', @EXEC_KEYWORD , '%')) \n");	            
        ELSEIF P_TYPE = '4' THEN
            SET @EXEC_KEYWORD  = P_KEYWORD;
            SET CNTSTRING = CONCAT(CNTSTRING, "AND    A.WTR_NM LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");	    
        END IF;
                        
    		SET @EXEC_CNT_SQL 	= CNTSTRING;
    		PREPARE STMT_CNT FROM  @EXEC_CNT_SQL;		
        EXECUTE STMT_CNT USING @EXEC_BOARD_SEQ_NO;
        DEALLOCATE PREPARE STMT_CNT;
        SET P_BOARD_CNT = @P_CNT;
        
    		SET SQLSTRING = CONCAT(SQLSTRING, "SELECT @ROWNUM := @ROWNUM+1 RM, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.BRD_NM, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.BRD_CD, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.CNTS_SEQ_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       Q.CNTS_ORD, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       Q.CNTS_DEPTH, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  			Q.CNTS_DEPTH, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  			Q.CNTS_TYPE, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  			Q.CNTS_KIND_CD, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  			Q.CNTS_WR_DPT, \n");        
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.CNTS_SUBJ, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.CNTS_MSG, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.ATTFILE_YN, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.REA_CNT, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.WTR_ID, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.WTR_NM, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.REG_TS, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.RPY_CNT,  \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       Q.NEW_DATA, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       Q.CNTS_WR_DPT_NM \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "       FROM (         \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "          SELECT (SELECT BRD_NM FROM BD_MANAGE WHERE BRD_CD = @EXEC_BOARD_SEQ_NO) AS BRD_NM, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.BRD_CD, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				       C.CNTS_SEQ_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.CNTS_ORD, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  				       IFNULL(A.CNTS_DEPTH, '') AS CNTS_DEPTH, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.CNTS_TYPE, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.CNTS_KIND_CD, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  				       (CASE WHEN A.CNTS_WR_DPT IS NULL OR A.CNTS_WR_DPT = '' THEN ''  \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  				            ELSE (SELECT D.DPT_NM FROM SN_DPT D WHERE D.DPT_NO = A.CNTS_WR_DPT) \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  				       END) AS CNTS_WR_DPT_NM, \n");  
        SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.CNTS_WR_DPT AS CNTS_WR_DPT, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.CNTS_SUBJ, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.CNTS_MSG, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.ATTFILE_YN, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.REA_CNT, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.WTR_ID, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				       A.WTR_NM, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				       DATE_FORMAT(A.REG_TS,'%Y-%m-%d') AS REG_TS, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "                 C.CNT AS RPY_CNT, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "                 CASE WHEN DATE_FORMAT(CURRENT_DATE(),'%Y-%m-%d') = DATE_FORMAT(A.REG_TS,'%Y-%m-%d') THEN 'Y' \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "                      ELSE 'N' \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "                 END NEW_DATA \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "  				  FROM BD_BOARD A, \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "            (SELECT B.BRD_CD, B.CNTS_SEQ_NO, COUNT(TBL.RPY_SEQ_NO) CNT \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "              FROM BD_REPLY TBL \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "              RIGHT JOIN BD_BOARD B \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "              ON TBL.CNTS_SEQ_NO = B.CNTS_SEQ_NO \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "              GROUP BY 2) C \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "            WHERE A.BRD_CD = @EXEC_BOARD_SEQ_NO AND A.CNTS_SEQ_NO = C.CNTS_SEQ_NO \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "            AND A.BRD_CD = @EXEC_BOARD_SEQ_NO \n");
    		
    		IF P_TYPE = '1' THEN
    		    SET @EXEC_KEYWORD  = P_KEYWORD;
    		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    A.CNTS_SUBJ LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
    		ELSEIF P_TYPE = '2' THEN
    		    SET @EXEC_KEYWORD  = P_KEYWORD;
    		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    A.CNTS_MSG LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
    		ELSEIF P_TYPE = '3' THEN
    		    SET @EXEC_KEYWORD  = P_KEYWORD;
    		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    (A.CNTS_SUBJ LIKE CONCAT('%', @EXEC_KEYWORD , '%') OR A.CNTS_MSG LIKE CONCAT('%', @EXEC_KEYWORD , '%')) \n");	
    		ELSEIF P_TYPE = '4' THEN
    		    SET @EXEC_KEYWORD  = P_KEYWORD;
    		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    A.WTR_NM LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");	             
    		END IF;
    		     
    		SET SQLSTRING = CONCAT(SQLSTRING, "            ORDER BY A.CNTS_ORD ASC \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "            LIMIT ?, ?) Q \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "      JOIN BD_BOARD B \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "      ON B.BRD_CD = Q.BRD_CD \n");
    		SET SQLSTRING = CONCAT(SQLSTRING, "      AND B.CNTS_SEQ_NO = Q.CNTS_SEQ_NO \n");
        
        IF P_BRD_CD = 'BBS01' THEN
    		  SET SQLSTRING = CONCAT(SQLSTRING, "            ORDER BY Q.CNTS_WR_DPT DESC, Q.CNTS_ORD ASC \n");        
        ELSE
    		  SET SQLSTRING = CONCAT(SQLSTRING, "      ORDER BY Q.CNTS_ORD ASC \n");        
        END IF;        
    		
                        
    		SET @EXEC_SQL 	= SQLSTRING;
    		PREPARE STMT FROM  @EXEC_SQL;		
        EXECUTE STMT USING @EXEC_ST, @EXEC_CNT;
    		DEALLOCATE PREPARE STMT;

    END IF;
    
 END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
