-- --------------------------------------------------------
-- 호스트:                          eberry.co.kr
-- 서버 버전:                        10.3.11-MariaDB - MariaDB Server
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 프로시저 REDSPUSH.GET_MEMBER_LIST_SEND_TARGET 구조 내보내기
DELIMITER //
CREATE DEFINER=`redspush`@`%` PROCEDURE `GET_MEMBER_LIST_SEND_TARGET`(
	IN `P_CPNY_NO` INTEGER,
  IN `P_TYPE` CHAR(1),  
  IN `P_KEYWORD` VARCHAR(100),
  IN `P_START_NO` INTEGER,
  IN `P_PAGE_NO` INTEGER,  
  OUT `P_USER_CNT` INTEGER,
	OUT `P_RESULT_ID` INTEGER,
	OUT `P_MESSAGE` VARCHAR(500)
)
    COMMENT '[neal] 푸시발송 대상 목록을 선택하기 위한 발송대상목록을 조회한다.'
BEGIN

    DECLARE SQLSTRING   TEXT;
    DECLARE CNTSTRING   TEXT;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
      BEGIN
        SET P_RESULT_ID	= -1;
        SET P_MESSAGE	= "조회중 오류가 발생하였습니다.";
    END;    
        
    SET SQLSTRING = "";  
    SET CNTSTRING = "";
        
    SET P_RESULT_ID= 0;
    SET P_MESSAGE= "정상적으로 처리되었습니다.";

		SET @EXEC_CPNY_NO  = P_CPNY_NO;
		SET @EXEC_ST  = P_START_NO;
		SET @EXEC_CNT  = P_PAGE_NO;            
    SET @ROWNUM =P_START_NO;
    
    SET CNTSTRING = CONCAT(CNTSTRING, "SELECT COUNT(A.ITEM_DIV) AS CNT \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "  INTO @P_CNT \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "  FROM ( \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "       SELECT 'C' AS ITEM_DIV,  \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "              A.CPNY_NO AS ITEM_ID,  \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "              C.CPNY_NM AS ITEM_NM,  \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "              NULL AS ITEM_DPT_NM, \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "              NULL AS CELL_NO,  \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "              NULL AS EMAIL_ADDR,  \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "              C.REG_TS AS REG_TS, \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "              COUNT(*) AS ITEM_CNT \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "         FROM SN_USR A, SN_COMPANY C \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "        WHERE A.CPNY_NO = C.CPNY_NO \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "          AND A.CPNY_NO = ? \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "     GROUP BY A.CPNY_NO, C.CPNY_NM \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "    UNION ALL  \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "       SELECT 'D', A.DPT_NO, B.DPT_NM, B.DPT_NM, NULL, NULL, B.REG_TS, COUNT(*) \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "         FROM SN_USR A, SN_DPT B \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "        WHERE A.DPT_NO = B.DPT_NO \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "          AND A.CPNY_NO = ? \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "     GROUP BY A.DPT_NO, B.DPT_NM \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "    UNION ALL \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "       SELECT 'P', A.USR_ID, A.USR_NM, B.DPT_NM, A.CELL_NO, A.EMAIL_ADDR, A.REG_TS, 1 \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "         FROM SN_USR A, SN_DPT B, SN_COMPANY C \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "        WHERE A.DPT_NO = B.DPT_NO \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "          AND A.CPNY_NO = C.CPNY_NO \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "          AND A.CPNY_NO = ? \n");
    SET CNTSTRING = CONCAT(CNTSTRING, ") A \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "WHERE 1=1 \n");
    
		IF P_TYPE = 'A' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET CNTSTRING = CONCAT(CNTSTRING, "AND    A.ITEM_NM LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
		ELSEIF P_TYPE = 'B' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET CNTSTRING = CONCAT(CNTSTRING, "AND    A.CELL_NO = @EXEC_KEYWORD \n");
		ELSEIF P_TYPE = 'C' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET CNTSTRING = CONCAT(CNTSTRING, "AND    A.EMAIL_ADDR LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");	   
		END IF;
                    
		SET @EXEC_CNT_SQL 	= CNTSTRING;
		PREPARE STMT_CNT FROM  @EXEC_CNT_SQL;		
    EXECUTE STMT_CNT USING @EXEC_CPNY_NO, @EXEC_CPNY_NO, @EXEC_CPNY_NO;
    DEALLOCATE PREPARE STMT_CNT;
    SET P_USER_CNT = @P_CNT;
    
    SET SQLSTRING = CONCAT(SQLSTRING, "SELECT @ROWNUM := @ROWNUM+1 RM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 A.ITEM_DIV, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 A.ITEM_ID, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 IFNULL(A.ITEM_NM, '') AS ITEM_NM, \n");    
    SET SQLSTRING = CONCAT(SQLSTRING, "			 CASE WHEN IFNULL(A.NCKNM_NM, '') = '' THEN A.ITEM_NM ELSE A.NCKNM_NM END AS NCKNM_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 IFNULL(A.IMG_PATH, '') AS IMG_PATH, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 IFNULL(A.ITEM_DPT_NM, '') AS ITEM_DPT_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 IFNULL(A.CELL_NO, '') AS CELL_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 IFNULL(A.EMAIL_ADDR, '') AS EMAIL_ADDR, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 IFNULL(DATE_FORMAT(A.REG_TS, '%Y-%m-%f'), '') AS REG_TS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 A.ITEM_CNT \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "  FROM ( \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       SELECT 'C' AS ITEM_DIV,  \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "              A.CPNY_NO AS ITEM_ID,  \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "              '전체회원' AS ITEM_NM,  \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "              C.CPNY_NM AS NCKNM_NM,  \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "              '' AS IMG_PATH,  \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "              NULL AS ITEM_DPT_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "              NULL AS CELL_NO,  \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "              NULL AS EMAIL_ADDR,  \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "              C.REG_TS AS REG_TS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "              COUNT(*) AS ITEM_CNT \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "         FROM SN_USR A, SN_COMPANY C \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "        WHERE A.CPNY_NO = C.CPNY_NO \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "          AND A.CPNY_NO = @EXEC_CPNY_NO \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "     GROUP BY A.CPNY_NO, C.CPNY_NM \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "    UNION ALL  \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       SELECT 'D', A.DPT_NO, B.DPT_NM, (SELECT D.CPNY_NM FROM SN_COMPANY D WHERE D.CPNY_NO = A.CPNY_NO) AS NCKNM_NM, '' AS IMG_PATH, B.DPT_NM, NULL, NULL, B.REG_TS, COUNT(*) \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "         FROM SN_USR A, SN_DPT B \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "        WHERE A.DPT_NO = B.DPT_NO \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "          AND A.CPNY_NO = @EXEC_CPNY_NO \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "     GROUP BY A.DPT_NO, B.DPT_NM \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "    UNION ALL \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       SELECT 'P', A.USR_ID, A.USR_NM, A.USR_NCKNM AS NCKNM_NM, A.AVT_IMG_PATH, B.DPT_NM, A.CELL_NO, A.EMAIL_ADDR, A.REG_TS, 1 \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "         FROM SN_USR A, SN_DPT B, SN_COMPANY C \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "        WHERE A.DPT_NO = B.DPT_NO \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "          AND A.CPNY_NO = C.CPNY_NO \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "          AND A.CPNY_NO = @EXEC_CPNY_NO \n");
    SET SQLSTRING = CONCAT(SQLSTRING, ") A \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "WHERE 1=1 \n");
    
		IF P_TYPE = 'A' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    A.ITEM_NM LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
		ELSEIF P_TYPE = 'B' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    A.CELL_NO = @EXEC_KEYWORD \n");
		ELSEIF P_TYPE = 'C' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    A.EMAIL_ADDR LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");	   
		END IF;
    
    SET SQLSTRING = CONCAT(SQLSTRING, "LIMIT ?, ? \n");
    
		SET @EXEC_SQL 	= SQLSTRING;
		PREPARE STMT FROM  @EXEC_SQL;		
    EXECUTE STMT USING @EXEC_ST, @EXEC_CNT;
		DEALLOCATE PREPARE STMT;
    
 END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
