-- --------------------------------------------------------
-- 호스트:                          eberry.co.kr
-- 서버 버전:                        10.3.11-MariaDB - MariaDB Server
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 프로시저 REDSPUSH.GET_RECV_HISTORY_LIST 구조 내보내기
DELIMITER //
CREATE DEFINER=`redspush`@`%` PROCEDURE `GET_RECV_HISTORY_LIST`(
	IN `P_USR_ID` VARCHAR(80),
  IN `P_CAT_CD` VARCHAR(1),
  IN `P_FROM_DT` VARCHAR(20),
  IN `P_TO_DT` VARCHAR(20),
  IN `P_START_NO` INTEGER,
  IN `P_PAGE_NO` INTEGER,  
  OUT `P_LIST_CNT` INTEGER,
	OUT `P_RESULT_ID` INTEGER,
	OUT `P_MESSAGE` VARCHAR(500)
)
    COMMENT '[oslee97] 발송이력 목록 조회.'
BEGIN

    DECLARE SQLSTRING   TEXT;
    DECLARE CNTSTRING   TEXT;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
      BEGIN
        SET P_RESULT_ID	= -1;
        SET P_MESSAGE	= "조회중 오류가 발생하였습니다.";
    END;    
        
    SET SQLSTRING = "";  
    SET CNTSTRING = "";
        
    SET P_RESULT_ID= 0;
    SET P_MESSAGE= "정상적으로 처리되었습니다.";

		SET @EXEC_USR_ID  = P_USR_ID;
		SET @EXEC_ST  = P_START_NO;
		SET @EXEC_CNT  = P_PAGE_NO;            
    SET @ROWNUM =P_START_NO;
    
    SET CNTSTRING = CONCAT(CNTSTRING, "		SELECT COUNT(A.RCVMSG_NO) AS CNT \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "     INTO @P_CNT \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "	  FROM PM_MSGRECV A, PM_MSGPLAN B, PM_MSGCNTS C \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "	 WHERE A.TRNS_NO = B.TRNS_NO \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "	   AND B.TRNS_NO = C.TRNS_NO \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "	   AND A.USR_ID = ? \n");
    
		IF P_CAT_CD != '' THEN
		    SET @EXEC_CAT_CD  = P_CAT_CD;
		    SET CNTSTRING = CONCAT(CNTSTRING, "AND    A.TRNS_CAT_CD = @EXEC_CAT_CD \n");
    END IF;
		IF P_FROM_DT != '' THEN
		    SET @EXEC_FROM_DT  = P_FROM_DT;
        SET @EXEC_TO_DT  = P_TO_DT;
		    SET CNTSTRING = CONCAT(CNTSTRING, "AND   DATE_FORMAT(A.RCV_TS, '%Y-%m-%d') BETWEEN @EXEC_FROM_DT AND @EXEC_TO_DT \n");	   
		END IF;
                    
		SET @EXEC_CNT_SQL 	= CNTSTRING;
		PREPARE STMT_CNT FROM  @EXEC_CNT_SQL;		
    EXECUTE STMT_CNT USING @EXEC_USR_ID;
    DEALLOCATE PREPARE STMT_CNT;
    SET P_LIST_CNT = @P_CNT;
    
    SET SQLSTRING = CONCAT(SQLSTRING, "SELECT @ROWNUM := @ROWNUM+1 RM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "			 T.RCVMSG_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.RCV_TS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.USR_ID, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.TRNS_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.READING_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.SNDMSG_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.TRNS_CAT_CD, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.TRNS_CAT_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.TRNS_STE, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.MSG_CAT, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.MSG_CAT_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.SND_USR_ID, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.SND_USR_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.SND_USR_NCKNM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.CPNY_MGR_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.DPT_MGR_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.AVT_IMG_PATH, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.MSG_SUBJ, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.MSG_CTNTS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.ATT_CAT_EXT \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "FROM( \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	SELECT A.RCVMSG_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       DATE_FORMAT(A.RCV_TS, '%Y-%m-%d %H:%i:%s') AS RCV_TS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(A.USR_ID, '') AS USR_ID, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(A.TRNS_NO, '') AS TRNS_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(A.READING_YN, 'N') AS READING_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(A.SNDMSG_NO, '') AS SNDMSG_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(B.TRNS_CAT_CD, '') AS TRNS_CAT_CD, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		     (CASE WHEN B.TRNS_CAT_CD = 'P' THEN 'PUSH' \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		           WHEN B.TRNS_CAT_CD = 'S' THEN 'SMS' \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		           WHEN B.TRNS_CAT_CD = 'M' THEN 'MMS' \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		           ELSE '' \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		      END) AS TRNS_CAT_NM, \n");    
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(B.TRNS_STE, '') AS TRNS_STE, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(B.MSG_CAT, '') AS MSG_CAT, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		     (CASE WHEN B.MSG_CAT = 'A' THEN '광고' \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		           WHEN B.MSG_CAT = 'B' THEN '업무' \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		           WHEN B.MSG_CAT = 'C' THEN '일정' \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		           WHEN B.MSG_CAT = 'E' THEN '기타' \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		           ELSE '' \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "		      END) AS MSG_CAT_NM, \n");     
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(B.SND_USR_ID, '') AS SND_USR_ID, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       (SELECT IFNULL(U.USR_NM, '') FROM SN_USR U WHERE U.USR_ID = B.SND_USR_ID) AS SND_USR_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       (SELECT IFNULL(U.USR_NCKNM, '') FROM SN_USR U WHERE U.USR_ID = B.SND_USR_ID) AS SND_USR_NCKNM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       (SELECT IFNULL(U.CPNY_MGR_YN, 'N') FROM SN_USR U WHERE U.USR_ID = B.SND_USR_ID) AS CPNY_MGR_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       (SELECT IFNULL(U.DPT_MGR_YN, 'N') FROM SN_USR U WHERE U.USR_ID = B.SND_USR_ID) AS DPT_MGR_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       (SELECT IFNULL(U.AVT_IMG_PATH, '') FROM SN_USR U WHERE U.USR_ID = B.SND_USR_ID) AS AVT_IMG_PATH, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(C.MSG_SUBJ, '') AS MSG_SUBJ, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(C.MSG_CTNTS, '') AS MSG_CTNTS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	       IFNULL(C.ATT_CAT_EXT, '') AS ATT_CAT_EXT \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	  FROM PM_MSGRECV A, PM_MSGPLAN B, PM_MSGCNTS C \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	 WHERE A.TRNS_NO = B.TRNS_NO \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	   AND B.TRNS_NO = C.TRNS_NO \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	   AND A.USR_ID = ? \n");
    SET SQLSTRING = CONCAT(SQLSTRING, ") T \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "	WHERE 1=1 \n");

		IF P_CAT_CD != '' THEN
		    SET @EXEC_CAT_CD  = P_CAT_CD;
		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    T.TRNS_CAT_CD = @EXEC_CAT_CD \n");
    END IF;
		IF P_FROM_DT != '' THEN
		    SET @EXEC_FROM_DT  = P_FROM_DT;
        SET @EXEC_TO_DT  = P_TO_DT;
		    SET SQLSTRING = CONCAT(SQLSTRING, "AND   DATE_FORMAT(T.RCV_TS, '%Y-%m-%d') BETWEEN @EXEC_FROM_DT AND @EXEC_TO_DT \n");	   
		END IF;

    SET SQLSTRING = CONCAT(SQLSTRING, "ORDER BY T.RCVMSG_NO DESC \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "LIMIT ?, ? \n");

		SET @EXEC_SQL 	= SQLSTRING;
		PREPARE STMT FROM  @EXEC_SQL;		
    EXECUTE STMT USING @EXEC_USR_ID, @EXEC_ST, @EXEC_CNT;
		DEALLOCATE PREPARE STMT;
    
 END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
