-- --------------------------------------------------------
-- 호스트:                          eberry.co.kr
-- 서버 버전:                        10.3.11-MariaDB - MariaDB Server
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 프로시저 REDSPUSH.GET_USER_LIST 구조 내보내기
DELIMITER //
CREATE DEFINER=`redspush`@`%` PROCEDURE `GET_USER_LIST`(
  IN `P_PROC_ID` VARCHAR(30)     ,
  IN `P_USR_NM` VARCHAR(50)     ,
  IN `P_USR_ID` VARCHAR(50)     ,
  IN `P_DEPT_CD` VARCHAR(50)     ,
  IN `P_START_NO` INT            ,
  IN `P_PAGE_NO` INT             ,
  IN `P_PAGING_YN` VARCHAR(1) ,
  OUT `P_USER_CNT` INT             ,
  OUT `P_RESULT_ID` INT             ,
  OUT `P_MESSAGE` TINYTEXT
)
BEGIN

    DECLARE SQLSTRING   TEXT;
    DECLARE CNTSTRING   TEXT;
    DECLARE O_COUNT      INT;
        
    SET SQLSTRING = "";  
    SET CNTSTRING = "";
    SET O_COUNT = 0;
    
    SET P_RESULT_ID= 0;
    SET P_MESSAGE= "정상적으로 처리되었습니다.";

    IF  P_PROC_ID = 'GET_USER_LIST' THEN       

        SET @EXEC_ST  = P_START_NO;
        SET @EXEC_CNT  = P_PAGE_NO;            
        SET @ROWNUM =P_START_NO;
        
        SET CNTSTRING = CONCAT(CNTSTRING, "SELECT COUNT(USR_ID) \n");      
        SET CNTSTRING = CONCAT(CNTSTRING, "  INTO    @P_CNT \n");     
        SET CNTSTRING = CONCAT(CNTSTRING, "  FROM SN_USR \n");     
        SET CNTSTRING = CONCAT(CNTSTRING, "  WHERE IFNULL(JOIN_STE_CD, '') != 'D' \n");
                
        IF P_USR_NM != '' THEN
            SET @EXEC_USR_NM  = P_USR_NM;
            SET CNTSTRING = CONCAT(CNTSTRING, "AND   USR_NM LIKE CONCAT('%', @EXEC_USR_NM , '%') \n");
        END IF;
        IF P_USR_ID != '' THEN
            SET @EXEC_USR_ID  = P_USR_ID;
            SET CNTSTRING = CONCAT(CNTSTRING, "AND    USR_ID LIKE CONCAT('%', @EXEC_USR_ID , '%') \n");
        END IF;
        IF P_DEPT_CD != '' THEN
            SET @EXEC_DEPT_CD  = P_DEPT_CD;
            SET CNTSTRING = CONCAT(CNTSTRING, "AND    CPNY_NO = @EXEC_DEPT_CD \n");      
        END IF;
       
                        
        SET @EXEC_CNT_SQL   = CNTSTRING;
        PREPARE STMT_CNT FROM  @EXEC_CNT_SQL; 
        EXECUTE STMT_CNT;
        DEALLOCATE PREPARE STMT_CNT;
        SET P_USER_CNT = @P_CNT;
        
        SET SQLSTRING = CONCAT(SQLSTRING, "SELECT @ROWNUM := @ROWNUM+1 RM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "				A.USR_ID, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_PW, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_NCKNM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_BIRDT, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_SEX, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.EMAIL_ADDR, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.CELL_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.TEL_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.POS_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DUTY_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.AVT_IMG_PATH, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.CPNY_MGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DPT_MGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.ACNT_KAKAO_LINK_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.ACNT_GOOGLE_LINK_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.PP_AGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.TOS_AGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DVC_AUTH_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.EMAIL_AUTH_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.JOIN_STE_CD, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.CPNY_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.CPNY_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DPT_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DPT_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.SYS_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.LATELY_CONN_TS, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.REG_TS, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.UPD_TS \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  FROM ( \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		SELECT USR_ID, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       USR_PW, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(USR_NM, '') AS USR_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(USR_NCKNM, USR_NM) AS USR_NCKNM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(USR_BIRDT, '') AS USR_BIRDT, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       USR_SEX, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(EMAIL_ADDR, '') AS EMAIL_ADDR, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(CELL_NO, '') AS CELL_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(TEL_NO, '') AS TEL_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(POS_NM, '') AS POS_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(DUTY_NM, '') AS DUTY_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(AVT_IMG_PATH, '') AS AVT_IMG_PATH, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(CPNY_MGR_YN, '') AS CPNY_MGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(DPT_MGR_YN, '') AS DPT_MGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       ACNT_KAKAO_LINK_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       ACNT_GOOGLE_LINK_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       PP_AGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       TOS_AGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       DVC_AUTH_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       EMAIL_AUTH_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "          IFNULL(JOIN_STE_CD, '') AS JOIN_STE_CD, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       CPNY_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       (CASE IFNULL(CPNY_NO, '') WHEN '' THEN '' ELSE (SELECT CPNY_NM FROM SN_COMPANY A WHERE A.CPNY_NO = SN_USR.CPNY_NO) END) AS CPNY_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       DPT_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       (CASE IFNULL(DPT_NO, '') WHEN '' THEN '' ELSE (SELECT DPT_NM FROM SN_DPT A WHERE A.CPNY_NO = SN_USR.CPNY_NO AND A.DPT_NO = SN_USR.DPT_NO) END) AS DPT_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       SYS_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(DATE_FORMAT(LATELY_CONN_TS, '%Y-%m-%d %H:%m:%s'), '') AS LATELY_CONN_TS, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       DATE_FORMAT(REG_TS, '%Y-%m-%d') AS REG_TS, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       DATE_FORMAT(UPD_TS, '%Y-%m-%d') AS UPD_TS \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		  FROM SN_USR \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "     WHERE IFNULL(JOIN_STE_CD, '') != 'D' \n");

        IF P_USR_NM != '' THEN
            SET @EXEC_USR_NM  = P_USR_NM;
            SET SQLSTRING = CONCAT(SQLSTRING, "AND   USR_NM LIKE CONCAT('%', @EXEC_USR_NM , '%') \n");
        END IF;
        IF P_USR_ID != '' THEN
            SET @EXEC_USR_ID  = P_USR_ID;
            SET SQLSTRING = CONCAT(SQLSTRING, "AND    USR_ID LIKE CONCAT('%', @EXEC_USR_ID , '%') \n");
        END IF;
        IF P_DEPT_CD != '' THEN
            SET @EXEC_DEPT_CD  = P_DEPT_CD;
            SET SQLSTRING = CONCAT(SQLSTRING, "AND    CPNY_NO = @EXEC_DEPT_CD \n");      
        END IF;
        
        SET SQLSTRING = CONCAT(SQLSTRING, "   ORDER BY USR_NM ASC \n");
        IF P_PAGING_YN != 'Y' THEN
          SET SQLSTRING = CONCAT(SQLSTRING, "   LIMIT  ?, ?  \n");
        END IF;
        SET SQLSTRING = CONCAT(SQLSTRING, "  ) A  \n");
                
        SET @EXEC_SQL   = SQLSTRING;
        PREPARE STMT FROM  @EXEC_SQL;   
        IF P_PAGING_YN != 'Y' THEN
          EXECUTE STMT USING @EXEC_ST, @EXEC_CNT;
        ELSE
          EXECUTE STMT;
        END IF;
        DEALLOCATE PREPARE STMT;

    ELSEIF  P_PROC_ID = 'GET_APVL_USER_LIST' THEN
        SET @EXEC_ST  = P_START_NO;
        SET @EXEC_CNT  = P_PAGE_NO;            
        SET @ROWNUM =P_START_NO;
        
        SET CNTSTRING = CONCAT(CNTSTRING, "SELECT COUNT(USR_ID) \n");      
        SET CNTSTRING = CONCAT(CNTSTRING, "  INTO    @P_CNT \n");     
        SET CNTSTRING = CONCAT(CNTSTRING, "  FROM SN_USR \n");     
        SET CNTSTRING = CONCAT(CNTSTRING, "  WHERE IFNULL(JOIN_STE_CD, '') != 'D' \n");
                
        IF P_USR_NM != '' THEN
            SET @EXEC_USR_NM  = P_USR_NM;
            SET CNTSTRING = CONCAT(CNTSTRING, "AND   USR_NM LIKE CONCAT('%', @EXEC_USR_NM , '%') \n");
        END IF;
        IF P_USR_ID != '' THEN
            SET @EXEC_USR_ID  = P_USR_ID;
            SET CNTSTRING = CONCAT(CNTSTRING, "AND    USR_ID LIKE CONCAT('%', @EXEC_USR_ID , '%') \n");
        END IF;
        IF P_DEPT_CD != '' THEN
            SET @EXEC_DEPT_CD  = P_DEPT_CD;
            SET CNTSTRING = CONCAT(CNTSTRING,  "AND    CPNY_NO =  @EXEC_DEPT_CD \n"); 
        END IF;
       
                        
        SET @EXEC_CNT_SQL   = CNTSTRING;
        PREPARE STMT_CNT FROM  @EXEC_CNT_SQL; 
        EXECUTE STMT_CNT;
        DEALLOCATE PREPARE STMT_CNT;
        SET P_USER_CNT = @P_CNT;
        
        SET SQLSTRING = CONCAT(SQLSTRING, "SELECT @ROWNUM := @ROWNUM+1 RM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "				A.USR_ID, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_PW, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_NCKNM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_BIRDT, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.USR_SEX, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.EMAIL_ADDR, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.CELL_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.TEL_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.POS_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DUTY_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.AVT_IMG_PATH, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.CPNY_MGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DPT_MGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.ACNT_KAKAO_LINK_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.ACNT_GOOGLE_LINK_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.PP_AGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.TOS_AGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DVC_AUTH_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.EMAIL_AUTH_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.JOIN_STE_CD, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.CPNY_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.CPNY_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DPT_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.DPT_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.SYS_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.LATELY_CONN_TS, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.REG_TS, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "       A.UPD_TS \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "  FROM ( \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		SELECT USR_ID, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       USR_PW, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(USR_NM, '') AS USR_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(USR_NCKNM, USR_NM) AS USR_NCKNM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(USR_BIRDT, '') AS USR_BIRDT, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       USR_SEX, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(EMAIL_ADDR, '') AS EMAIL_ADDR, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(CELL_NO, '') AS CELL_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(TEL_NO, '') AS TEL_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(POS_NM, '') AS POS_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(DUTY_NM, '') AS DUTY_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(AVT_IMG_PATH, '') AS AVT_IMG_PATH, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(CPNY_MGR_YN, '') AS CPNY_MGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(DPT_MGR_YN, '') AS DPT_MGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       ACNT_KAKAO_LINK_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       ACNT_GOOGLE_LINK_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       PP_AGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       TOS_AGR_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       DVC_AUTH_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       EMAIL_AUTH_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "          IFNULL(JOIN_STE_CD, '') AS JOIN_STE_CD, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       CPNY_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       (CASE IFNULL(CPNY_NO, '') WHEN '' THEN '' ELSE (SELECT CPNY_NM FROM SN_COMPANY A WHERE A.CPNY_NO = SN_USR.CPNY_NO) END) AS CPNY_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       DPT_NO, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       (CASE IFNULL(DPT_NO, '') WHEN '' THEN '' ELSE (SELECT DPT_NM FROM SN_DPT A WHERE A.CPNY_NO = SN_USR.CPNY_NO AND A.DPT_NO = SN_USR.DPT_NO) END) AS DPT_NM, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       SYS_YN, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       IFNULL(DATE_FORMAT(LATELY_CONN_TS, '%Y-%m-%d %H:%m:%s'), '') AS LATELY_CONN_TS, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       DATE_FORMAT(REG_TS, '%Y-%m-%d') AS REG_TS, \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		       DATE_FORMAT(UPD_TS, '%Y-%m-%d') AS UPD_TS \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "		  FROM SN_USR \n");
        SET SQLSTRING = CONCAT(SQLSTRING, "     WHERE IFNULL(JOIN_STE_CD, '') != 'D' \n");
  
        IF P_USR_NM != '' THEN
            SET @EXEC_USR_NM  = P_USR_NM;
            SET SQLSTRING = CONCAT(SQLSTRING, "AND   USR_NM LIKE CONCAT('%', @EXEC_USR_NM , '%') \n");
        END IF;
        IF P_USR_ID != '' THEN
            SET @EXEC_USR_ID  = P_USR_ID;
            SET SQLSTRING = CONCAT(SQLSTRING, "AND    USR_ID LIKE CONCAT('%', @EXEC_USR_ID , '%') \n");
        END IF;
        IF P_DEPT_CD != '' THEN
            SET @EXEC_DEPT_CD  = P_DEPT_CD;
            SET SQLSTRING = CONCAT(SQLSTRING,  "AND    CPNY_NO =  @EXEC_DEPT_CD \n"); 
        END IF;
        
        SET SQLSTRING = CONCAT(SQLSTRING, "   ORDER BY USR_NM ASC \n");
        
        IF P_PAGING_YN != 'Y' THEN
          SET SQLSTRING = CONCAT(SQLSTRING, "   LIMIT  ?, ?  \n");
        END IF;
        
        SET SQLSTRING = CONCAT(SQLSTRING, "  ) A  \n");
                
        SET @EXEC_SQL   = SQLSTRING;
        PREPARE STMT FROM  @EXEC_SQL;   
        IF P_PAGING_YN != 'Y' THEN
          EXECUTE STMT USING @EXEC_ST, @EXEC_CNT;
        ELSE
          EXECUTE STMT;          
        END IF;
        DEALLOCATE PREPARE STMT;  
    
    ELSE 
        SET P_RESULT_ID= -1;
        SET P_MESSAGE= "매개변수를 확인해주시기 바랍니다.";
    END IF;
    
 END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
