-- --------------------------------------------------------
-- 호스트:                          eberry.co.kr
-- 서버 버전:                        10.3.11-MariaDB - MariaDB Server
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 프로시저 REDSPUSH.GET_TEMPLATE_LIST 구조 내보내기
DELIMITER //
CREATE DEFINER=`redspush`@`%` PROCEDURE `GET_TEMPLATE_LIST`(
	IN `P_USR_ID` VARCHAR(80),
  IN `P_TYPE` CHAR(1),  
  IN `P_KEYWORD` VARCHAR(100),
  IN `P_START_NO` INTEGER,
  IN `P_PAGE_NO` INTEGER,  
  OUT `P_LIST_CNT` INTEGER,
	OUT `P_RESULT_ID` INTEGER,
	OUT `P_MESSAGE` VARCHAR(500)
)
    COMMENT '[oslee97] 템플릿 설정 목록 조회.'
BEGIN

    DECLARE SQLSTRING   TEXT;
    DECLARE CNTSTRING   TEXT;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
      BEGIN
        SET P_RESULT_ID	= -1;
        SET P_MESSAGE	= "조회중 오류가 발생하였습니다.";
    END;    
        
    SET SQLSTRING = "";  
    SET CNTSTRING = "";
        
    SET P_RESULT_ID= 0;
    SET P_MESSAGE= "정상적으로 처리되었습니다.";

		SET @EXEC_WTR_ID  = P_USR_ID;
		SET @EXEC_ST  = P_START_NO;
		SET @EXEC_CNT  = P_PAGE_NO;            
    SET @ROWNUM =P_START_NO;
    
    SET CNTSTRING = CONCAT(CNTSTRING, "SELECT COUNT(A.MSGPLN_NO) AS CNT \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "  INTO @P_CNT \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "  FROM PM_TMPLATMSG A \n");
    SET CNTSTRING = CONCAT(CNTSTRING, "WHERE WTR_ID = ? \n");
    
		IF P_TYPE = 'A' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET CNTSTRING = CONCAT(CNTSTRING, "AND    A.MSG_SUBJ LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
		ELSEIF P_TYPE = 'B' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET CNTSTRING = CONCAT(CNTSTRING, "AND    A.MSG_CTNTS LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
		ELSEIF P_TYPE = 'C' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET CNTSTRING = CONCAT(CNTSTRING, "AND   ( A.MSG_SUBJ LIKE CONCAT('%', @EXEC_KEYWORD , '%') OR A.MSG_CTNTS LIKE CONCAT('%', @EXEC_KEYWORD , '%')) \n");	   
		END IF;
                    
		SET @EXEC_CNT_SQL 	= CNTSTRING;
		PREPARE STMT_CNT FROM  @EXEC_CNT_SQL;		
    EXECUTE STMT_CNT USING @EXEC_WTR_ID;
    DEALLOCATE PREPARE STMT_CNT;
    SET P_LIST_CNT = @P_CNT;
    
    SET SQLSTRING = CONCAT(SQLSTRING, "SELECT @ROWNUM := @ROWNUM+1 RM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.MSGPLN_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.WTR_ID, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.RCVGRP_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.TMPLAT_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.MSG_CTNTS_CAT, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.MSG_CTNTS_CAT_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.TRNS_MTHD_TYPE, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.TRNS_MTHD_TYPE_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.RPT_TRNS_RULE, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.RESE_TRNS_TS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.PUSH_TRNS_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.PUSH_TRNS_YN_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.SMS_TRNS_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.SMS_TRNS_YN_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.MSG_SUBJ, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.MSG_CTNTS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.ATT_CAT_EXT, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.ATT_FILE_PATH, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.MSG_CTNTS_ATTR, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.REG_TS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       A.UPD_TS \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "  FROM ( \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "SELECT T.MSGPLN_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.WTR_ID, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.RCVGRP_NO, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.TMPLAT_NM, '') AS TMPLAT_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.MSG_CTNTS_CAT, '') AS MSG_CTNTS_CAT, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       CASE WHEN T.MSG_CTNTS_CAT = 'A' THEN '광고' WHEN T.MSG_CTNTS_CAT = 'B' THEN '업무'  WHEN T.MSG_CTNTS_CAT = 'C' THEN '일정'  WHEN T.MSG_CTNTS_CAT = 'D' THEN '기타' ELSE '' END AS MSG_CTNTS_CAT_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.TRNS_MTHD_TYPE, '') AS TRNS_MTHD_TYPE, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       CASE WHEN T.TRNS_MTHD_TYPE = 'D' THEN '즉시발송' WHEN T.TRNS_MTHD_TYPE = 'R' THEN '예약발송'  WHEN T.TRNS_MTHD_TYPE = 'P' THEN '반복발송' ELSE '' END AS TRNS_MTHD_TYPE_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.RPT_TRNS_RULE, '') AS RPT_TRNS_RULE, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.RESE_TRNS_TS, '') AS RESE_TRNS_TS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.PUSH_TRNS_YN, '') AS PUSH_TRNS_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       CASE WHEN IFNULL(T.PUSH_TRNS_YN, '') = 'Y' THEN '푸시메세지' ELSE '' END AS PUSH_TRNS_YN_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.SMS_TRNS_YN, '') AS SMS_TRNS_YN, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       CASE WHEN IFNULL(T.SMS_TRNS_YN, '') = 'Y' THEN 'SMS' ELSE '' END AS SMS_TRNS_YN_NM, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.MSG_SUBJ, '') AS MSG_SUBJ, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.MSG_CTNTS, '') AS MSG_CTNTS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.ATT_CAT_EXT, '') AS ATT_CAT_EXT, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.ATT_FILE_PATH, '') AS ATT_FILE_PATH, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       IFNULL(T.MSG_CTNTS_ATTR, '') AS MSG_CTNTS_ATTR, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.REG_TS, \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "       T.UPD_TS \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "  FROM PM_TMPLATMSG T \n");
    SET SQLSTRING = CONCAT(SQLSTRING, " WHERE T.WTR_ID = @EXEC_WTR_ID \n");
    SET SQLSTRING = CONCAT(SQLSTRING, ") A \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "WHERE 1=1 \n");    
    
		IF P_TYPE = 'A' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    A.MSG_SUBJ LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
		ELSEIF P_TYPE = 'B' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET SQLSTRING = CONCAT(SQLSTRING, "AND    A.MSG_CTNTS LIKE CONCAT('%', @EXEC_KEYWORD , '%') \n");
		ELSEIF P_TYPE = 'C' THEN
		    SET @EXEC_KEYWORD  = P_KEYWORD;
		    SET SQLSTRING = CONCAT(SQLSTRING, "AND   ( A.MSG_SUBJ LIKE CONCAT('%', @EXEC_KEYWORD , '%') OR A.MSG_CTNTS LIKE CONCAT('%', @EXEC_KEYWORD , '%')) \n");	   
		END IF;

    SET SQLSTRING = CONCAT(SQLSTRING, "ORDER BY A.MSGPLN_NO DESC \n");
    SET SQLSTRING = CONCAT(SQLSTRING, "LIMIT ?, ? \n");

		SET @EXEC_SQL 	= SQLSTRING;
		PREPARE STMT FROM  @EXEC_SQL;		
    EXECUTE STMT USING @EXEC_ST, @EXEC_CNT;
		DEALLOCATE PREPARE STMT;
    
 END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
