-- --------------------------------------------------------
-- 호스트:                          eberry.co.kr
-- 서버 버전:                        10.3.11-MariaDB - MariaDB Server
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 프로시저 REDSPUSH.GET_STAT_TRANS_REQ 구조 내보내기
DELIMITER //
CREATE DEFINER=`redspush`@`%` PROCEDURE `GET_STAT_TRANS_REQ`(
    IN `P_PROC_ID`    VARCHAR(30),
    IN `P_FROM_DT`    VARCHAR(8),
    IN `P_TO_DT`      VARCHAR(8),
    OUT P_RESULT_ID     INT,
    OUT P_MESSAGE       TINYTEXT
)
    COMMENT '[oslee] 일별/주별/월별/년도별로 시간대별 발송요청 통계 조회'
BEGIN

    DECLARE SQLSTRING   TEXT;
    DECLARE CNTSTRING   TEXT;
    DECLARE O_COUNT      INT;
        
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
      BEGIN
        SET P_RESULT_ID	= -1;
        SET P_MESSAGE	= "조회중 오류가 발생하였습니다.";
    END;    
    
    SET SQLSTRING = "";  
    SET CNTSTRING = "";
    SET O_COUNT = 0;
    
    SET P_RESULT_ID= 0;
    SET P_MESSAGE= "정상적으로 처리되었습니다.";
    
    SET @EXEC_FROM = P_FROM_DT;
    SET @EXEC_TO = P_TO_DT;

    IF  P_PROC_ID != 'STAT_TRANS_WEEK' THEN

      SET SQLSTRING = CONCAT(SQLSTRING, "SELECT (CASE GB WHEN 'B' THEN '계' ELSE C.DATE END) AS '날짜', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.TOT), 0) AS '계', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.0H), 0) AS '0시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.1H), 0) AS '1시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.2H), 0) AS '2시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.3H), 0) AS '3시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.4H), 0) AS '4시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.5H), 0) AS '5시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.6H), 0) AS '6시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.7H), 0) AS '7시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.8H), 0) AS '8시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.9H), 0) AS '9시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.10H), 0) AS '10시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.11H), 0) AS '11시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.12H), 0) AS '12시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.13H), 0) AS '13시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.14H), 0) AS '14시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.15H), 0) AS '15시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.16H), 0) AS '16시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.17H), 0) AS '17시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.18H), 0) AS '18시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.19H), 0) AS '19시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.20H), 0) AS '20시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.21H), 0) AS '21시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.22H), 0) AS '22시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.23H), 0) AS '23시' \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "FROM (   \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "  SELECT DATE,  \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         (A.0H +A.1H+A.2H+A.3H+A.4H+A.5H+A.6H+A.7H+A.8H+A.9H+A.10H+A.11H+A.12H+A.13H+A.14H+A.15H+A.16H+A.17H+A.18H+A.19H+A.20H+A.21H+A.22H+A.23H) AS TOT, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         A.0H,A.1H,A.2H,A.3H,A.4H,A.5H,A.6H,A.7H,A.8H,A.9H,A.10H,A.11H,A.12H,A.13H,A.14H,A.15H,A.16H,A.17H,A.18H,A.19H,A.20H,A.21H,A.22H,A.23H     \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "  FROM( \n");
      
      IF  P_PROC_ID = 'STAT_TRANS_YEAR' THEN
        SET SQLSTRING = CONCAT(SQLSTRING, "  SELECT DATE_FORMAT(TRNS_REQ_TS,'%Y') AS DATE,  \n");
      ELSEIF  P_PROC_ID = 'STAT_TRANS_MONTH' THEN
        SET SQLSTRING = CONCAT(SQLSTRING, "  SELECT DATE_FORMAT(TRNS_REQ_TS,'%Y-%m') AS DATE,  \n");
      ELSEIF  P_PROC_ID = 'STAT_TRANS_DAY' THEN
        SET SQLSTRING = CONCAT(SQLSTRING, "  SELECT DATE_FORMAT(TRNS_REQ_TS,'%Y-%m-%d') AS DATE,  \n");
      END IF;
      
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 0 THEN 1 ELSE 0 END) AS 0H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 1 THEN 1 ELSE 0 END) AS 1H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 2 THEN 1 ELSE 0 END) AS 2H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 3 THEN 1 ELSE 0 END) AS 3H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 4 THEN 1 ELSE 0 END) AS 4H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 5 THEN 1 ELSE 0 END) AS 5H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 6 THEN 1 ELSE 0 END) AS 6H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 7 THEN 1 ELSE 0 END) AS 7H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 8 THEN 1 ELSE 0 END) AS 8H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 9 THEN 1 ELSE 0 END) AS 9H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 10 THEN 1 ELSE 0 END) AS 10H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 11 THEN 1 ELSE 0 END) AS 11H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 12 THEN 1 ELSE 0 END) AS 12H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 13 THEN 1 ELSE 0 END) AS 13H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 14 THEN 1 ELSE 0 END) AS 14H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 15 THEN 1 ELSE 0 END) AS 15H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 16 THEN 1 ELSE 0 END) AS 16H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 17 THEN 1 ELSE 0 END) AS 17H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 18 THEN 1 ELSE 0 END) AS 18H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 19 THEN 1 ELSE 0 END) AS 19H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 20 THEN 1 ELSE 0 END) AS 20H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 21 THEN 1 ELSE 0 END) AS 21H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 22 THEN 1 ELSE 0 END) AS 22H, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 23 THEN 1 ELSE 0 END) AS 23H \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "  FROM PM_MSGPLAN  \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "  WHERE DATE_FORMAT(TRNS_REQ_TS,'%Y%m%d') BETWEEN @EXEC_FROM AND @EXEC_TO \n");
--       SET SQLSTRING = CONCAT(SQLSTRING, "    AND TRNS_STE = 'S' \n");
      
      IF  P_PROC_ID = 'STAT_TRANS_YEAR' THEN
        SET SQLSTRING = CONCAT(SQLSTRING, "  GROUP BY DATE_FORMAT(TRNS_REQ_TS,'%Y') \n");
      ELSEIF  P_PROC_ID = 'STAT_TRANS_MONTH' THEN
        SET SQLSTRING = CONCAT(SQLSTRING, "  GROUP BY DATE_FORMAT(TRNS_REQ_TS,'%Y-%m') \n");
      ELSEIF  P_PROC_ID = 'STAT_TRANS_DAY' THEN
        SET SQLSTRING = CONCAT(SQLSTRING, "  GROUP BY DATE_FORMAT(TRNS_REQ_TS,'%Y-%m-%d') \n");        
      END IF;
      
      SET SQLSTRING = CONCAT(SQLSTRING, "  ) A        \n");
      SET SQLSTRING = CONCAT(SQLSTRING, ") C, \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "  (SELECT 'A' GB FROM DUAL \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "    UNION ALL SELECT 'B' GB FROM DUAL ) B \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "    GROUP BY (CASE B.GB WHEN 'A' THEN C.DATE END)  \n");

  		SET @EXEC_SQL 	= SQLSTRING;
  		PREPARE STMT FROM  @EXEC_SQL;		
      EXECUTE STMT;
  		DEALLOCATE PREPARE STMT;

    ELSE
      -- 주별통계
      SET SQLSTRING = CONCAT(SQLSTRING, "SELECT (CASE GB WHEN 'B' THEN '계' ELSE C.START END) AS '시작일자', \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "        (CASE GB WHEN 'B' THEN '계' ELSE C.END END) AS '종료일자', \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.TOT), 0) AS '계', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.0H), 0) AS '0시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.1H), 0) AS '1시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.2H), 0) AS '2시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.3H), 0) AS '3시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.4H), 0) AS '4시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.5H), 0) AS '5시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.6H), 0) AS '6시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.7H), 0) AS '7시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.8H), 0) AS '8시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.9H), 0) AS '9시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.10H), 0) AS '10시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.11H), 0) AS '11시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.12H), 0) AS '12시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.13H), 0) AS '13시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.14H), 0) AS '14시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.15H), 0) AS '15시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.16H), 0) AS '16시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.17H), 0) AS '17시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.18H), 0) AS '18시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.19H), 0) AS '19시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.20H), 0) AS '20시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.21H), 0) AS '21시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.22H), 0) AS '22시', \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "        COALESCE(SUM(C.23H), 0) AS '23시' \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "FROM (   \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "  SELECT START, \n");  
      SET SQLSTRING = CONCAT(SQLSTRING, "         END,  \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         (A.0H +A.1H+A.2H+A.3H+A.4H+A.5H+A.6H+A.7H+A.8H+A.9H+A.10H+A.11H+A.12H+A.13H+A.14H+A.15H+A.16H+A.17H+A.18H+A.19H+A.20H+A.21H+A.22H+A.23H) AS TOT, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         A.0H,A.1H,A.2H,A.3H,A.4H,A.5H,A.6H,A.7H,A.8H,A.9H,A.10H,A.11H,A.12H,A.13H,A.14H,A.15H,A.16H,A.17H,A.18H,A.19H,A.20H,A.21H,A.22H,A.23H     \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "  FROM( \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "  SELECT DATE_FORMAT(DATE_SUB(TRNS_REQ_TS, INTERVAL (DAYOFWEEK(TRNS_REQ_TS)-1) DAY), '%Y-%m-%d') AS START,  \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         DATE_FORMAT(DATE_SUB(TRNS_REQ_TS, INTERVAL (DAYOFWEEK(TRNS_REQ_TS)-7) DAY), '%Y-%m-%d') AS END,  \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         DATE_FORMAT(TRNS_REQ_TS, '%Y%U') AS TT, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 0 THEN 1 ELSE 0 END) AS 0H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 1 THEN 1 ELSE 0 END) AS 1H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 2 THEN 1 ELSE 0 END) AS 2H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 3 THEN 1 ELSE 0 END) AS 3H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 4 THEN 1 ELSE 0 END) AS 4H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 5 THEN 1 ELSE 0 END) AS 5H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 6 THEN 1 ELSE 0 END) AS 6H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 7 THEN 1 ELSE 0 END) AS 7H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 8 THEN 1 ELSE 0 END) AS 8H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 9 THEN 1 ELSE 0 END) AS 9H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 10 THEN 1 ELSE 0 END) AS 10H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 11 THEN 1 ELSE 0 END) AS 11H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 12 THEN 1 ELSE 0 END) AS 12H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 13 THEN 1 ELSE 0 END) AS 13H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 14 THEN 1 ELSE 0 END) AS 14H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 15 THEN 1 ELSE 0 END) AS 15H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 16 THEN 1 ELSE 0 END) AS 16H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 17 THEN 1 ELSE 0 END) AS 17H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 18 THEN 1 ELSE 0 END) AS 18H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 19 THEN 1 ELSE 0 END) AS 19H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 20 THEN 1 ELSE 0 END) AS 20H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 21 THEN 1 ELSE 0 END) AS 21H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 22 THEN 1 ELSE 0 END) AS 22H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 23 THEN 1 ELSE 0 END) AS 23H, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "         SUM(CASE WHEN HOUR(TRNS_REQ_TS) = 24 THEN 1 ELSE 0 END) AS 24H  \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "  FROM PM_MSGPLAN  \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "  WHERE DATE_FORMAT(TRNS_REQ_TS,'%Y%m%d') BETWEEN @EXEC_FROM AND @EXEC_TO \n");
      SET SQLSTRING = CONCAT(SQLSTRING, "  GROUP BY TT \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "  ) A        \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, ") C, \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "  (SELECT 'A' GB FROM DUAL \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "    UNION ALL SELECT 'B' GB FROM DUAL ) B \n"); 
      SET SQLSTRING = CONCAT(SQLSTRING, "    GROUP BY (CASE B.GB WHEN 'A' THEN C.START END)  \n");       
      
  		SET @EXEC_SQL 	= SQLSTRING;
  		PREPARE STMT FROM  @EXEC_SQL;		
      EXECUTE STMT;
  		DEALLOCATE PREPARE STM;     
  
    END IF;
    
 END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
