-- --------------------------------------------------------
-- 호스트:                          eberry.co.kr
-- 서버 버전:                        10.3.11-MariaDB - MariaDB Server
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 테이블 REDSPUSH.SN_CONFIG 구조 내보내기
CREATE TABLE IF NOT EXISTS `SN_CONFIG` (
  `CNF_CD` varchar(5) COLLATE utf8_bin DEFAULT NULL COMMENT '설정 코드 ',
  `CNF_NM` varchar(60) COLLATE utf8_bin DEFAULT NULL COMMENT '설정 명 ',
  `CNF_VALUE` text COLLATE utf8_bin DEFAULT NULL COMMENT '설정 값 '
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='환경설정';

-- 테이블 데이터 REDSPUSH.SN_CONFIG:~6 rows (대략적) 내보내기
/*!40000 ALTER TABLE `SN_CONFIG` DISABLE KEYS */;
INSERT INTO `SN_CONFIG` (`CNF_CD`, `CNF_NM`, `CNF_VALUE`) VALUES
	('HOME', 'tjdtmddn', '[{"cols":33,"rows":45,"y":0,"x":0,"group":"C","categorize":"C","url":"stat/getMsgCatStat","title":"발송 방법 통계 차트","value":"","no":1,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":33,"group":"C","categorize":"C","url":"stat/getTransTypeStat","title":"메세지 유형 통계 차트","value":"","no":2,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":66,"group":"C","categorize":"P","url":"stat/getMainTransTime","title":"시간대별 발송요청 차트","value":"","no":3,"chartValue":null},{"cols":33,"rows":20,"y":45,"x":0,"group":"B","categorize":"N","url":"board/getMainBoardList","title":"공지사항","value":"","no":8},{"cols":33,"rows":20,"y":45,"x":33,"group":"B","categorize":"Q","url":"board/getMainBoardList","title":"Q&A","value":"","no":9},{"cols":33,"rows":20,"y":45,"x":66,"group":"B","categorize":"S","url":"board/getMainBoardList","title":"시스템 장애신고","value":"","no":10}]'),
	('HOME', 'skarjsdn', '[{"cols":33,"rows":45,"y":0,"x":0,"group":"C","categorize":"C","url":"stat/getMsgCatStat","title":"발송 방법 통계 차트","value":"","no":1,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":33,"group":"C","categorize":"C","url":"stat/getTransTypeStat","title":"메세지 유형 통계 차트","value":"","no":2,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":66,"group":"C","categorize":"P","url":"stat/getMainTransTime","title":"시간대별 발송요청 차트","value":"","no":3,"chartValue":null},{"cols":33,"rows":20,"y":45,"x":0,"group":"B","categorize":"N","url":"board/getMainBoardList","title":"공지사항","value":"","no":8},{"cols":33,"rows":20,"y":45,"x":33,"group":"B","categorize":"Q","url":"board/getMainBoardList","title":"Q&A","value":"","no":9},{"cols":33,"rows":20,"y":45,"x":66,"group":"B","categorize":"S","url":"board/getMainBoardList","title":"시스템 장애신고","value":"","no":10}]'),
	('HOME', 'admin', '[{"cols":33,"rows":45,"y":0,"x":0,"group":"C","categorize":"C","url":"stat/getMsgCatStat","title":"발송 방법 통계 차트","value":"","no":1,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":66,"group":"C","categorize":"C","url":"stat/getTransTypeStat","title":"메세지 유형 통계 차트","value":"","no":2,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":33,"group":"C","categorize":"P","url":"stat/getMainTransTime","title":"시간대별 발송요청 차트","value":"","no":3,"chartValue":null},{"cols":33,"rows":20,"y":45,"x":66,"group":"B","categorize":"N","url":"board/getMainBoardList","title":"공지사항","value":"","no":8},{"cols":33,"rows":20,"y":45,"x":33,"group":"B","categorize":"Q","url":"board/getMainBoardList","title":"Q&A","value":"","no":9},{"cols":33,"rows":20,"y":45,"x":0,"group":"B","categorize":"S","url":"board/getMainBoardList","title":"시스템 장애신고","value":"","no":10}]'),
	('HOME', 'mhyoon', '[{"cols":25,"rows":8,"y":0,"x":0,"group":"S","categorize":"completed","url":"stat/getMainStat","title":"발송완료","value":"","no":1},{"cols":25,"rows":8,"y":0,"x":25,"group":"S","categorize":"ongoing","url":"stat/getMainStat","title":"발송대기","value":"","no":2},{"cols":25,"rows":8,"y":0,"x":50,"group":"S","categorize":"reserved","url":"stat/getMainStat","title":"발송예약","value":"","no":3},{"cols":24,"rows":8,"y":0,"x":75,"group":"S","categorize":"failed","url":"stat/getMainStat","title":"SMS","value":"","no":4},{"cols":33,"rows":45,"y":8,"x":0,"group":"C","categorize":"C","url":"stat/getMsgCatStat","title":"발송 방법 통계 차트","value":"","no":5,"chartValue":null},{"cols":33,"rows":45,"y":8,"x":33,"group":"C","categorize":"C","url":"stat/getTransTypeStat","title":"메세지 유형 통계 차트","value":"","no":6,"chartValue":null},{"cols":33,"rows":45,"y":8,"x":66,"group":"C","categorize":"P","url":"stat/getMainTransTime","title":"시간대별 발송요청 차트","value":"","no":7,"chartValue":null},{"cols":33,"rows":20,"y":53,"x":0,"group":"B","categorize":"N","url":"board/getMainBoardList","title":"공지사항","value":"","no":12},{"cols":33,"rows":20,"y":53,"x":33,"group":"B","categorize":"Q","url":"board/getMainBoardList","title":"Q&A","value":"","no":13},{"cols":33,"rows":20,"y":53,"x":66,"group":"B","categorize":"S","url":"board/getMainBoardList","title":"시스템 장애신고","value":"","no":14}]'),
	('HOME', 'jhlee@eberry.co.kr', '[{"cols":33,"rows":45,"y":0,"x":0,"group":"C","categorize":"C","url":"stat/getMsgCatStat","title":"발송 방법 통계 차트","value":"","no":1,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":33,"group":"C","categorize":"C","url":"stat/getTransTypeStat","title":"메세지 유형 통계 차트","value":"","no":2,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":66,"group":"C","categorize":"P","url":"stat/getMainTransTime","title":"시간대별 발송요청 차트","value":"","no":3,"chartValue":null},{"cols":33,"rows":20,"y":45,"x":0,"group":"B","categorize":"N","url":"board/getMainBoardList","title":"공지사항","value":"","no":8},{"cols":33,"rows":20,"y":45,"x":33,"group":"B","categorize":"Q","url":"board/getMainBoardList","title":"Q&A","value":"","no":9},{"cols":33,"rows":20,"y":45,"x":66,"group":"B","categorize":"S","url":"board/getMainBoardList","title":"시스템 장애신고","value":"","no":10}]'),
	('HOME', 'oslee97@eberry.co.kr', '[{"cols":33,"rows":45,"y":0,"x":0,"group":"C","categorize":"C","url":"stat/getMsgCatStat","title":"발송 방법 통계 차트","value":"","no":1,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":33,"group":"C","categorize":"C","url":"stat/getTransTypeStat","title":"메세지 유형 통계 차트","value":"","no":2,"chartValue":null},{"cols":33,"rows":45,"y":0,"x":66,"group":"C","categorize":"P","url":"stat/getMainTransTime","title":"시간대별 발송요청 차트","value":"","no":3,"chartValue":null},{"cols":33,"rows":20,"y":45,"x":0,"group":"B","categorize":"N","url":"board/getMainBoardList","title":"공지사항","value":"","no":8},{"cols":33,"rows":20,"y":45,"x":33,"group":"B","categorize":"Q","url":"board/getMainBoardList","title":"Q&A","value":"","no":9},{"cols":33,"rows":20,"y":45,"x":66,"group":"B","categorize":"S","url":"board/getMainBoardList","title":"시스템 장애신고","value":"","no":10}]');
/*!40000 ALTER TABLE `SN_CONFIG` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
